language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-18mode
  - jruby-19mode

script: bundle exec rake test

branches:
  only:
    - master

notifications:
  email:
    - iqvoc@innoq.com
